# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



# Keyboard Layout
input {
    kb_layout = us
    kb_variant = intl
}

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

# Autostart
exec-once = waybar
exec-once = awww-daemon && sleep 1 && awww img /home/gabriel/Downloads/2.jpg
# Clipboard and Sync
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --watch wl-copy --primary


gestures {
    # 4 dedos para cambiar de escritorio
    gesture = 4, horizontal, workspace

    # 3 dedos para Firefox (usando wtype)
    gesture = 3, up, dispatcher, exec, wtype -M ctrl t -m ctrl
    gesture = 3, down, dispatcher, exec, wtype -M ctrl w -m ctrl
    gesture = 3, left, dispatcher, exec, wtype -M ctrl -k Page_Down -m ctrl
    gesture = 3, right, dispatcher, exec, wtype -M ctrl -k Page_Up -m ctrl
    
    workspace_swipe_distance = 300
    workspace_swipe_invert = false
}

# Basic Binds
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, exec, wlogout
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, movefocus, d # O podrías dejarlo libre, lo muevo a focus down por si acaso o simplemente lo borro
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, Tab, exec, /home/gabriel/.local/bin/smart_tab.sh
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, B, exec, firefox
bind = $mainMod, N, exec, /home/gabriel/.local/bin/rotate_wallpaper.sh
bind = $mainMod CONTROL, up, fullscreen, 1
bind = $mainMod CONTROL, down, fullscreen, 1

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Switch workspaces with mainMod + [0-5]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [0-5]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
