-- Generated by nwg-displays on 2026-05-22 at 07:33:29. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3000x2000@59.98",
    position = "1920x0",
    scale = 2.0
})
hl.monitor({
    output = "DP-1",
    disabled = true
})
