# Matrix theme
background #000000
foreground #00FF41
selection_background #005C0C
selection_foreground #00FF41
url_color #008F11
cursor #00FF41
cursor_text_color #000000

# Tabs
active_tab_background #00FF41
active_tab_foreground #000000
inactive_tab_background #005C0C
inactive_tab_foreground #008F11

# Windows
active_border_color #00FF41
inactive_border_color #005C0C

# normal
color0 #000000
color1 #FF0000
color2 #00FF41
color3 #FFB000
color4 #008F11
color5 #00FF41
color6 #008F11
color7 #00FF41

# bright
color8  #005C0C
color9  #FF0000
color10 #00FF41
color11 #FFB000
color12 #008F11
color13 #00FF41
color14 #008F11
color15 #00FF41
