tab_bar_edge            top

tab_bar_background      #11111b
active_tab_foreground   #11111b
active_tab_background   #cdd6f4
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825

tab_bar_style           powerline
tab_powerline_style     slanted


background_opacity 0.9

# --- Configuración del Cursor ---
# Estilo de cursor (puedes usar block, beam o underline)
cursor_shape block

# Animación de estela (Cursor Trail)
# El primer valor es la sensibilidad (1 es muy sensible)
cursor_trail 3
# Tiempo de desvanecimiento (min y max en segundos)
cursor_trail_decay 0.1 0.4
# Distancia mínima para que empiece la estela (en celdas)
cursor_trail_start_threshold 2

# --- Rendimiento y Fluidez ---
# Reduce el retraso de repintado para animaciones más suaves
repaint_delay 10
# Sincronización con la tasa de refresco del monitor
sync_to_monitor yes
