# BEGIN_KITTY_THEME
# Matrix
include current-theme.conf
# END_KITTY_THEME

font_family RobotoMono Nerd Font Mono
font_size 11.0

tab_bar_style           powerline
tab_powerline_style     slanted

tab_bar_edge            top

background_opacity 0.9

copy_on_select yes

# --- Clic derecho para pegar (estilo Windows) ---
mouse_map right press ungrabbed paste_from_clipboard

# --- Configuración del Cursor ---
# Estilo de cursor (puedes usar block, beam o underline)
cursor_shape block

# Animación de estela (Cursor Trail)
# El primer valor es la sensibilidad (1 es muy sensible)
cursor_trail 3
# Tiempo de desvanecimiento (min y max en segundos)
cursor_trail_decay 0.1 0.4
# Distancia mínima para que empiece la estela (en celdas)
cursor_trail_start_threshold 2

